# Generated by Django 4.2.5 on 2023-10-05 17:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='user',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='member',
            name='accumulations',
            field=models.CharField(max_length=30, verbose_name='Accumulations'),
        ),
        migrations.AlterField(
            model_name='member',
            name='address',
            field=models.CharField(max_length=100, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='member',
            name='date_of_birth',
            field=models.DateField(verbose_name='Date of Birth'),
        ),
        migrations.AlterField(
            model_name='member',
            name='effective_date',
            field=models.DateField(verbose_name='Effective Date'),
        ),
        migrations.AlterField(
            model_name='member',
            name='eligibility',
            field=models.CharField(choices=[('Active', 'Active'), ('Terminated', 'Terminated')], max_length=30, verbose_name='Eligibility'),
        ),
        migrations.AlterField(
            model_name='member',
            name='first_name',
            field=models.CharField(max_length=30, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='member',
            name='last_name',
            field=models.CharField(max_length=30, verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='member',
            name='patient_id',
            field=models.CharField(max_length=30, verbose_name='Patient ID'),
        ),
        migrations.AlterField(
            model_name='member',
            name='phone_number',
            field=models.CharField(max_length=30, verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='member',
            name='relation',
            field=models.CharField(choices=[('Policy Holder', 'Policy Holder'), ('Dependent Spouse', 'Dependent Spouse'), ('Dependent Daughter', 'Dependent Daughter'), ('Dependent Son', 'Dependent Son')], max_length=30, verbose_name='Relation'),
        ),
        migrations.AlterField(
            model_name='member',
            name='ssn',
            field=models.CharField(max_length=30, verbose_name='SSN'),
        ),
        migrations.AlterField(
            model_name='member',
            name='termination_date',
            field=models.DateField(verbose_name='Termination Date'),
        ),
    ]
