# Generated by Django 4.2.5 on 2023-10-05 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_member_user_alter_member_accumulations_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='date_of_birth',
            field=models.DateField(help_text='Required. Enter your date of birth'),
        ),
    ]
