# Generated by Django 4.2.5 on 2023-11-12 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_alter_member_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('npi', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('phoneNumber', models.CharField(max_length=20)),
            ],
        ),
    ]
