# Generated by Django 4.2.6 on 2023-11-19 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_provider'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coverage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(max_length=255)),
                ('coverage', models.FloatField()),
                ('after_deductible', models.FloatField()),
                ('copay', models.FloatField()),
                ('cpt_codes', models.CharField(max_length=255)),
            ],
        ),
    ]
