# Generated by Django 4.2.5 on 2023-12-10 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_coverage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nurse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('patient_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='coverage',
            name='copay',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='coverage',
            name='coverage',
            field=models.CharField(max_length=255),
        ),
    ]
